### ISSUE TITLE
Various warning and error messages

### ISSUE THREAD

**Issue by francicco** [theaidenlab/juicer#120]
Hi,

I'm trying to run `Juicer` in order to use `3d-dna`. Everything seems to work fine with the data you provide, but when I execute it on my data I get a number or warning messages and some errors. The main file for 3d-dna `merged_nodups.txt` is there but for same reasons the run has problems.

```
Skipping Scf0008823	1000	538299569	1000	1001
Skipping Scf0008824	1000	538300582	1000	1001
Skipping Scf0008825	1000	538301595	1000	1001
Skipping Scf0008826	1000	538302608	1000	1001
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1762)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1531)
	at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:944)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:661)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:122)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)
./scripts/common/juicer_tools is post-processing Hi-C for Diul
Data read from /home/fc464/rds/rds-shm37-helixmbodyw/HeliconiiniProg/Diul.Assembly-Supernova10x/Diul.Juicer/aligned/inter_30.hic.
Motifs read from ./references/motif

ARROWHEAD:

Picked up _JAVA_OPTIONS: -Xmx16384m
WARN [2019-07-03T09:26:01,051]  [Globals.java:138] [main]  Development mode is enabled
Reading file: /home/fc464/rds/rds-shm37-helixmbodyw/HeliconiiniProg/Diul.Assembly-Supernova10x/Diul.Juicer/aligned/inter_30.hic
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:474)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:236)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:60)
	at juicebox.tools.clt.juicer.Arrowhead.readJuicerArguments(Arrowhead.java:135)
	at juicebox.tools.clt.JuicerCLT.readArguments(JuicerCLT.java:66)
	at juicebox.tools.HiCTools.main(HiCTools.java:95)
***! Problem while running Arrowhead
(-: Pipeline successfully completed (-:
```

Attached the entire log file
Thanks for your help
F
[Juicer.Diul.log](https://github.com/aidenlab/juicer/files/3354687/Juicer.Diul.log)

**Comment by nchernia** [comment]
Please ask this on our forum #64
