### ISSUE TITLE
java.lang.NumberFormatException: For input string: "2493839898"

### ISSUE THREAD

**Issue by wlhCNU** [theaidenlab/juicer#129]
conmmond:
java -jar juicer_tools_1.11.04_jcuda.0.8.jar pre  data/test.txt data/test.hic  chromosome_sizes.tsv

The content of the file chromosome_sizes.tsv is :
super_scaffold   2493839898

error report:
WARN [2019-08-22T17:45:46,004]  [Globals.java:138] [main]  Development mode is enabled
java.lang.NumberFormatException: For input string: "2493839898"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at juicebox.data.HiCFileTools.loadChromosomes(HiCFileTools.java:159)
        at juicebox.tools.clt.old.PreProcessing.readArguments(PreProcessing.java:87)
        at juicebox.tools.HiCTools.main(HiCTools.java:95)

It seems that the number '2493839898' is beyond the maximum size of an integer.  Can we change the pre software integer to long ?
Thanks

**Comment by nchernia** [comment]
@dudcha what is the status with this?
