### ISSUE TITLE
Error Using Pre to get hic data

### ISSUE THREAD

**Issue by sshen82** [theaidenlab/juicer#150]
Hi,
I was working on this data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124391, but encountered an error as below:
.java.lang.ArrayIndexOutOfBoundsException: Index 88 out of bounds for length 79
	at juicebox.tools.utils.original.ExpectedValueCalculation.addDistance(ExpectedValueCalculation.java:171)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.incrementCount(Preprocessor.java:1660)
	at juicebox.tools.utils.original.Preprocessor$MatrixPP.incrementCount(Preprocessor.java:1501)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:767)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:124)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)

The code I wrote is like this:
#!/bin/bash
FILES=`ls /p/keles/schic/volumeB/Ecker2019/mouse/GSE124391/*.txt`
for f in $FILES
do
        java -Xmx2g -jar ~/Rfile/juicerdir/scripts/common/juicer_tools.jar pre -q 30 $f $f.hic mm10
done

I have put the reference for mm10 in the folder, and the txt file is supposed to be correct. What do you think is the problem of this?

[GSM3531602_181102_snm3C_D8_AD006_indexed_contacts.txt.TXT.txt.txt](https://github.com/aidenlab/juicer/files/3991807/GSM3531602_181102_snm3C_D8_AD006_indexed_contacts.txt.TXT.txt.txt)

**Comment by sshen82** [comment]
It seems that it is the problem of reference, when I use hg18, it works, but I did downloaded all the mm10 files.

**Comment by sa501428** [comment]
Hi @sshen82 , Juicer Tools Pre doesn't use the reference genome, only the chrom.sizes. For general usage questions, please post to our forum: aidenlab.org/forum.html
