### ISSUE TITLE
 java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mibiledna** [theaidenlab/juicer#152]
Dear All,
         When I run juicer, I meet the following errors (java version: openjdk version "1.8.0_171"):

        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)
.//scripts/common/juicer_tools is post-processing Hi-C for hg19
Data read from ../HiC/aligned/inter_30.hic.
Motifs read from .//references/motif

ARROWHEAD:

Picked up _JAVA_OPTIONS: -Xmx16384m
Reading file: ../HiC/aligned/inter_30.hic
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:468)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:235)
        at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
        at juicebox.tools.clt.juicer.Arrowhead.run(Arrowhead.java:184)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)
***! Problem while running Arrowhead
***! Error! The statistics do not add up. Alignment likely failed to complete on one or more files. Run relaunch_prep.sh
Stats don't add up.  Check ../HiC/aligned for results

Did anybody have a idea on what is wrong? Thanks!

Cheng

**Comment by sa501428** [comment]
Questions should be posted to the forum at aidenlab.org/forum.html
Github Issues is for bug reports
