### ISSUE TITLE
Could not read hic file: No enum constant juicebox.windowui.NormalizationType.SCALE

### ISSUE THREAD

**Issue by mihuzx** [theaidenlab/juicer#187]
Hi there,

I converted the validpairs file from hicpro to validpairs.hic for juicerbox, then I wanted to use hiccups call loops, but get this error "Could not read hic file: No enum constant juicebox.windowui.NormalizationType.SCALE"

Thanks for your help.
Xuan

**Comment by sa501428** [comment]
What version of the juicer tools jar are you using?
Also, please use the forum for general questions - aidenlab.org/forum.html

**Comment by sa501428** [comment]
Should be resolved in the latest jars.

**Comment by zzhoujialu** [comment]
Sorry, I am new here...I met the same error. 
I  used the following command and met the foloowing error:
java -Djava.awt.headless=true  -Xmx16000m  -jar /path/to/juicer_tools_1.22.01.jar dump observed KR /path/to/a.hic 1 1 BP 5000 /path/to/a.KRobserved

Exception in thread "main" java.lang.UnsupportedClassVersionError: juicebox/tools/HiCTools : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Do you have any idea of what could be causing the error?
Looking forward to hearing from you.
Thanks!
