### ISSUE TITLE
juicer_tools NullPointerException at zoom FRAG_20

### ISSUE THREAD

**Issue by esebesty** [theaidenlab/juicer#233]
I'm trying to convert HiC-Pro result matrices to Juicebox format, using the `hicpro2juicebox.sh` script, available [here](https://github.com/nservant/HiC-Pro/blob/master/bin/utils/hicpro2juicebox.sh).

However, I'm getting a NullPointerException.

<details>
  <summary>Error message</summary>

```
HiC-Pro format > 2.7.5 detected ...
Generating Juicebox input files ...
Running Juicebox ...
WARN [2021-07-27T19:02:37,145]  [Globals.java:138] [main]  Development mode is enabled
Using 1 CPU thread(s)
Start preprocess
Writing header
Writing body
......................................................................................................................................................................................................................................................................................................................................
Writing footer
nBytesV5: 1893810
masterIndexPosition: 706792378

Finished preprocess

Calculating norms for zoom BP_2500000
Calculating norms for zoom BP_1000000
Calculating norms for zoom BP_500000
Calculating norms for zoom BP_250000
Calculating norms for zoom BP_100000
Calculating norms for zoom BP_50000
Calculating norms for zoom BP_25000
Calculating norms for zoom BP_10000
Calculating norms for zoom BP_5000
Calculating norms for zoom BP_1000
Calculating norms for zoom FRAG_500
Calculating norms for zoom FRAG_200
Calculating norms for zoom FRAG_100
Calculating norms for zoom FRAG_50
Calculating norms for zoom FRAG_20java.lang.NullPointerException
        at juicebox.data.iterator.ListOfListIterator.hasNext(ListOfListIterator.java:45)
        at juicebox.data.iterator.IteratorContainer.getNumberOfContactRecords(IteratorContainer.java:51)
        at juicebox.data.iterator.ListOfListIteratorContainer.getIsThereEnoughMemoryForNormCalculation(ListOfListIteratorContainer.java:52)
        at juicebox.tools.utils.norm.NormalizationCalculations.<init>(NormalizationCalculations.java:59)
        at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:178)
        at juicebox.tools.clt.old.AddNorm.launch(AddNorm.java:87)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:170)
        at juicebox.tools.HiCTools.main(HiCTools.java:94)
done !
```
</details>

and I end up with a partial `.hic` file. Opened an [issue](https://github.com/nservant/HiC-Pro/issues/463) in the HiC-Pro repo, but this might be a more relevant place.

The exact command line I'm using:

```sh
~/work/repos/bcro/bit-bio/hicpro-install/HiC-Pro/bin/utils/hicpro2juicebox.sh -i dataset.allValidPairs -g ~/work/repos/bcro/bit-bio/hicpro-install/HiC-Pro/annotation/chrom_hg19.sizes -j ~/work/repos/bcro/bit-bio/juicebox/juicer_tools.2.10.01.jar -r ~/work/repos/bcro/bit-bio/hicpro-install/HiC-Pro/annotation/HindIII_resfrag_hg19.bed
```

Software versions
- juicer_tools.2.10.01.jar
- openjdk version "1.8.0_112"
- OpenJDK Runtime Environment (Zulu 8.19.0.1-linux64) (build 1.8.0_112-b16)
- OpenJDK 64-Bit Server VM (Zulu 8.19.0.1-linux64) (build 25.112-b16, mixed mode)
- Amazon LInux AMI 2018.03

**Comment by sa501428** [comment]
Can you try building without the restriction fragment file? 

Also, the latest 2.x jar has some things that could break when used with other tools. If building without the fragment file doesn't work, you could try using the latest 1.x jar.

**Comment by esebesty** [comment]
Works without the restriction fragment file, thanks!
