### ISSUE TITLE
Still have problem with cuda installation 

### ISSUE THREAD

**Issue by Lattesnow** [theaidenlab/juicer#237]
Hi, I am using the CPU model to run my hic data. I installed the cuda and with a Nivida GPU here. But it still shows no detect the GPU with the errors showing below.

 java -jar juicer_tools_1.22.01.jar hiccups -r 40000 -p 1 -i 3 -f 0.1 -d 80000 --ignore-sparsity dmsoshallowhg38new.hic dmsohiccups_40kb
WARN [2021-08-25T15:32:01,774]  [Globals.java:138] [main]  Development mode is enabled
Reading file: dmsoshallowhg38new.hic
Resolution 40000 not available.
No valid configurations specified, using default settings
Using 1 CPU thread(s)
Warning Hi-C map is too sparse to find many loops via HiCCUPS.
Default settings for 5kb, 10kb, and 25kb being used
Running HiCCUPS for resolution 5000
Data not available for chr6 at 5000 resolution
Data not available for chr9 at 5000 resolution
Data not available for chr18 at 5000 resolution
Data not available for chr22 at 5000 resolution
Data not available for chrX at 5000 resolution
Data not available for chrY at 5000 resolution
jcuda.CudaException: Failed to initialize the driver: CUDA_ERROR_NO_DEVICE
        at jcuda.utils.KernelLauncher.initialize(KernelLauncher.java:606)
        at jcuda.utils.KernelLauncher.<init>(KernelLauncher.java:586)
        at jcuda.utils.KernelLauncher.create(KernelLauncher.java:393)
        at jcuda.utils.KernelLauncher.create(KernelLauncher.java:321)
        at jcuda.utils.KernelLauncher.compile(KernelLauncher.java:270)
        at juicebox.tools.utils.juicer.hiccups.GPUController.<init>(GPUController.java:72)
        at juicebox.tools.clt.juicer.HiCCUPS.buildGPUController(HiCCUPS.java:578)
        at juicebox.tools.clt.juicer.HiCCUPS.runCoreCodeForHiCCUPS(HiCCUPS.java:505)
        at juicebox.tools.clt.juicer.HiCCUPS.access$200(HiCCUPS.java:158)
        at juicebox.tools.clt.juicer.HiCCUPS$1.run(HiCCUPS.java:434)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
GPU/CUDA Installation Not Detected
Exiting HiCCUPS

**Comment by sa501428** [comment]
Have you already tested the installation using something like this:
https://github.com/sa501428/GPUTest

**Comment by sa501428** [comment]
Also how was this file built? Have you posted this question to the Google Forum? aidenlab.org/forum.html

**Comment by Lattesnow** [comment]
> Have you already tested the installation using something like this:
> https://github.com/sa501428/GPUTest

This test shows my GPU is not installed or activated

**Comment by sa501428** [comment]
So this means there's either an issue with the CUDA installation, your GPU, or something upstream. It's not a Juicer issue. You could try using the CPU version of HiCCUPS while you get the GPU installation fixed. https://github.com/aidenlab/juicer/wiki/CPU-HiCCUPS

Also please use the forum for general questions.

**Comment by Lattesnow** [comment]
> So this means there's either an issue with the CUDA installation, your GPU, or something upstream. It's not a Juicer issue. You could try using the CPU version of HiCCUPS while you get the GPU installation fixed. https://github.com/aidenlab/juicer/wiki/CPU-HiCCUPS
> 
> Also please use the forum for general questions.

thanks for the reply I will try the CPU version of Hiccups
