### ISSUE TITLE
java error while running juicer on cluster

### ISSUE THREAD

**Issue by BijalThakkar** [theaidenlab/juicer#285]
Dear Juicer team,

I am running HiC data using CPU version on our server system at Ugent. Can you tell me am i doing anything wrong here or is it a memory issue.

*******************************************************************************************************************************
[Experiment]$ less 118/log.txt 

        at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:84)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)

real    0m1.973s
user    0m0.899s
sys     0m0.394s
Tue Jul  5 23:12:44 CEST 2022
Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
Not including fragment map
Error while reading graphs file: java.io.FileNotFoundException: /data/gent/Test_Bijal/Experiment/118/aligned/inter_30_hists.m (No such file or directory)
Start preprocess
Writing header
Writing body
/data/gent/Test_Bijal/scripts/common/juicer_tools: line 24: 3590737 Killed                  java -Djava.awt.headless=true -Djava.library.path=`dirname $0`/lib64 -Ddevelopment=false -jar `dirname $0`/juicer_tools.jar $*

real    0m30.377s
user    0m23.094s
sys     0m9.693s
Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
Error reading datasetnull
java.io.EOFException
        at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
        at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:127)
        at juicebox.tools.utils.original.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:78)
        at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:84)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)

real    0m2.084s
user    0m0.909s
sys     0m0.367s
/data/Test_Bijal/scripts/common/juicer_tools is post-processing Hi-C for hg19
Data read from /data/Test_Bijal/Experiment/118/aligned/inter_30.hic.
Motifs read from /data/Test_Bijal/references/motif

ARROWHEAD:

Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
Exception in thread "main" jargs.gnu.CmdLineParser$IllegalOptionValueException: Illegal value '/data/Test_Bijal/Experiment/118/aligned/inter_30.hic' for option -z/--threads
        at jargs.gnu.CmdLineParser$Option$IntegerOption.parseValue(CmdLineParser.java:202)
        at jargs.gnu.CmdLineParser$Option.getValue(CmdLineParser.java:157)
        at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:485)
        at jargs.gnu.CmdLineParser.parse(CmdLineParser.java:426)
        at juicebox.tools.HiCTools.main(HiCTools.java:61)
***! Problem while running Arrowhead
***! Error! Either inter.hic or inter_30.hic were not created
Either inter.hic or inter_30.hic were not created.  Check  for results

*******************************************************************************************************************************
i would appreciate if you look into this matter.

Regards
Bijal Thakkar

**Comment by Theo-wang0007** [comment]
I also encountered this problem when running ARROWHEAD. There is no "merged_nodups.txt" in aligned.

**Comment by GrassW** [comment]
> I also encountered this problem when running ARROWHEAD. There is no "merged_nodups.txt" in aligned.

Hi,
I met the problem of "no merged_nodups.txt", too. That is because I didn't use "-assembly" to produce "old style merged_nodups", as they said in the "--help".
I guess you can either,
1. Add "-assembly" when you restart to run juicer.sh .
2. Execute this command line under the working folder, 
`samtools view -@ ${ThreadsNum} -O SAM -F 1024 aligned/merged_dedup.*am | awk -v mnd=1 -f ${juiceDir}/scripts/sam_to_pre.awk > aligned/merged_nodups.txt`
, modified from line #1929 of SLURM/scripts/juicer.sh .

I choose 2 to save my time.
