### ISSUE TITLE
> Unknown command: statistics

### ISSUE THREAD

**Issue by qdu-beep** [theaidenlab/juicer#323]
I have encountered some problems while using the juicer.
I hope you can help me to confirm whether my operation is correct, thank you for your help！
I cloned the github repo for Juicer. (git clone https://github.com/aidenlab/juicer.git)
And, I placed this Git repository in software/ directory.  In another directory juicer_work/ I created, I set up the references/ , restriction_sites/ , and work/ directories. 

In  juicer_work/ : ln -s /home/dq/software/juicer/CPU scripts
I have the same problem as agilly, I downloaded the Juicer Tools jar 1.9.9 in the juicer_work/scripts/common/ .  However, I found that the file juicer/work/aligned/inter.hic is still being generated continuously, and other files have not been generated new content after the error is reported, such as "inter.txt".

If I should download the latest version and re-run juicer.sh?

In the juicer_work/scripts/common/ : 
wget https://github.com/aidenlab/Juicebox/releases/download/v2.20.00/juicer_tools.2.20.00.jar
ln -s juicer_tools.2.20.00.jar  juicer_tools.jar

export PATH=/home/dq/software/juicer/:$PATH
export PATH=/home/dq/software/miniconda3/envs/juicer/bin/:$PATH
/juicer_work/scripts/juicer.sh \
-g genomic \
-z /juicer_work/references/genomic.fna \
-p /juicer_work/restriction_sites/chrom.sizes \
-y /juicer_work/restriction_sites/DpnII.txt \
-s DpnII \
-d /juicer_work/work \
-D /juicer_work/ \
-t 90

Thank you so much for taking the time to answer my question, I have another doubt.

In the output log file:
" (-: Aligning files matching /juicer_work/work/fastq/*_R*.fastq* to genome /juicer_work/references/genomic.fna with no fragment delimited maps."
In the website https://github.com/aidenlab/juicer/wiki/Installation:
"(If you don't use fragment delimited resolutions, you must run Juicer with the -x flag)"

I'm not sure if it's my restriction file not being used during the juicer run.

My output log file content is as follows:
Using /juicer_work/restriction_sites/DpnII.txt as site file
(-: Looking for fastq files...fastq files exist
(-: Created /juicer_work/work/splits.
(-: Aligning files matching /juicer_work/work/fastq/*_R*.fastq*
 to genome  /juicer_work/references/genomic.fna with no fragment delimited maps.
Running command bwa mem -SP5M -t 90 -R @RG\tID:13271\tSM:HiC_sample\tPL:ILM\tLB:HiC_library  /juicer_work/references/genomic.fna  /juicer_work/work/splits/13271_R1.fastq.gz  /juicer_work/work/splits/13271_R2.fastq.gz >  /juicer_work/work/splits/13271.fastq.gz.sam
(-:  Align of  /juicer_work/work/splits/13271.fastq.gz.sam done successfully
(-: Finished sorting all sorted files into a single merge.
(-:  Mark duplicates done successfully
Not including fragment map
Start preprocess
Writing header
Writing body

My error output log file content is as follows:
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -K 320000000 -SP5M -t 90 -R @RG\tID:13271\tSM:HiC_sample\tPL:ILM\tLB:HiC_library  /juicer_work/references/genomic.fna  /juicer_work/work/splits/13271_R1.fastq.gz  /juicer_work/work/splits/13271_R2.fastq.gz
[main] Real time: 29331.845 sec; CPU: 2567696.332 sec
[bam_sort_core] merging from 17 files and 90 in-memory blocks...
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:98)
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:98)
Picked up _JAVA_OPTIONS: -Xmx150000m -Xms150000m
Error while reading graphs file: java.io.FileNotFoundException:  /juicer_work/work/aligned/inter_hists.m (No such file or directory)

_Originally posted by @qdu-beep in https://github.com/aidenlab/juicer/issues/263#issuecomment-1668866028_

**Comment by BRNiu** [comment]
Hello! I have encountered the same problem with yours. How did you solve it?
