### ISSUE TITLE
Calculating norms for zoom BP_100000java.lang.ArrayIndexOutOfBoundsException: 1296

### ISSUE THREAD

**Issue by maize821** [theaidenlab/juicer#324]
![图片](https://github.com/aidenlab/juicer/assets/68184101/981023a9-60ae-4323-be7a-f5864d327131)
I'm having trouble converting pairs to hic files, this is the content of my pair file, when I use the following command `java -Xmx2g -jar juicer_tools.1.9.9_jcuda.0.8.jar pre ./test.pair test.hic mm10` gives the following error
`Not including fragment map
Start preprocess
Writing header
Writing body
...............................
Writing footer

Finished preprocess

Calculating norms for zoom BP_2500000
Calculating norms for zoom BP_1000000
Calculating norms for zoom BP_500000
Calculating norms for zoom BP_250000
Calculating norms for zoom BP_100000java.lang.ArrayIndexOutOfBoundsException: 1296
        at juicebox.tools.utils.original.NormalizationCalculations.computeVC(NormalizationCalculations.java:319)
        at juicebox.tools.utils.original.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:161)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:121)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)
`
I speculate that there may be a problem with normalize. When I add `-n`, this error will not appear. I hope to get your answer

**Comment by maize821** [comment]
![图片](https://github.com/aidenlab/juicer/assets/68184101/248b220c-7a07-4b4e-8421-a4c0f36ab2da)
