### ISSUE TITLE
GPU/CUDA Installation Not Detected

### ISSUE THREAD

**Issue by tarak77** [theaidenlab/juicer#325]
Hi, I am trying to run HICCUPS on a test insitu hic data downloaded from 4DN portal on my LSF cluster. After loading the java and cuda modules, I try to run an interactive session on GPU and get the following error

```
[shisodet@lilac-ln02 insitu_hic]$ bsub -R "rusage[mem=40]" -q gpuqueue -R "gpu||A100||A40" -gpu "num=1" -W 4:00 -Is bash
Job <19519945> is submitted to queue <gpuqueue>.
<<Waiting for dispatch ...>>
<<Starting on lj14>>
[shisodet@lj14 insitu_hic]$ 
[shisodet@lj14 insitu_hic]$ java -Xmx10g -jar /data/deyk/tarak/juicer_tools_1.22.01.jar hiccups --ignore-sparsity ./test/4DNFI4OUMWZ8/4DNFI4OUMWZ8.hic ./test/4DNFI4OUMWZ8/
WARN [2023-08-29T14:13:00,285]  [Globals.java:138] [main]  Development mode is enabled
Reading file: ./test/4DNFI4OUMWZ8/4DNFI4OUMWZ8.hic
No valid configurations specified, using default settings
Using 1 CPU thread(s)
Default settings for 5kb, 10kb, and 25kb being used
Running HiCCUPS for resolution 5000
Data not available for Y at 5000 resolution
4% 
9% 
14% 
19% 
24% 
29% 
34% 
39% 
44% 
49% 
54% 
59% 
64% 
69% 
74% 
79% 
84% 
89% 
94% 
99% 
jcuda.CudaException: Failed to create a context: INVALID CUresult: 46
	at jcuda.utils.KernelLauncher.createContext(KernelLauncher.java:650)
	at jcuda.utils.KernelLauncher.initialize(KernelLauncher.java:626)
	at jcuda.utils.KernelLauncher.<init>(KernelLauncher.java:586)
	at jcuda.utils.KernelLauncher.create(KernelLauncher.java:393)
	at jcuda.utils.KernelLauncher.create(KernelLauncher.java:321)
	at jcuda.utils.KernelLauncher.compile(KernelLauncher.java:270)
	at juicebox.tools.utils.juicer.hiccups.GPUController.<init>(GPUController.java:72)
	at juicebox.tools.clt.juicer.HiCCUPS.buildGPUController(HiCCUPS.java:578)
	at juicebox.tools.clt.juicer.HiCCUPS.runCoreCodeForHiCCUPS(HiCCUPS.java:505)
	at juicebox.tools.clt.juicer.HiCCUPS.access$200(HiCCUPS.java:158)
	at juicebox.tools.clt.juicer.HiCCUPS$1.run(HiCCUPS.java:434)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
GPU/CUDA Installation Not Detected
Exiting HiCCUPS

```

Any help will be great

**Comment by adamcatto** [comment]
Hey @tarak77 did you end up resolving this issue? Our lab is running into the same issue. nvidia-smi can find the GPU (V100) but HiCCUPS is giving the same `GPU/CUDA Installation Not Detected` error.

**Comment by tarak77** [comment]
@adamcatto unfortunately no. I don't remember exactly now but I think I used the CPU version

**Comment by Isoris** [comment]
you can edit the juicer hiccups and pass the --CPU argument

**Comment by starrzy** [comment]
I add this before running hiccups (`hiccups` depends on `LD_LIBRARY_PATH` to find CUDA), and it works:
```
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export PATH=$CUDA_HOME/bin:$PATH
```
