### ISSUE TITLE
***! Error! Either inter.hic or inter_30.hic were not created

### ISSUE THREAD

**Issue by yuntan1992** [theaidenlab/juicer#330]
Hi, 
I get this error.
Error while reading graphs file: java.io.FileNotFoundException: /share/home/qiuyuntan/juicer/work/noz/aligned/inter_hists.m (No such file or directory)
And 
***! Error! Either inter.hic or inter_30.hic were not created
Either inter.hic or inter_30.hic were not created.  Check  for results
Actually, the inter.hic or inter_30.hic does exist.
![image](https://github.com/aidenlab/juicer/assets/73515361/b7f0b8ef-61df-4479-9a4f-8786bd788740)

here is the running log
[juicer.log](https://github.com/aidenlab/juicer/files/12668150/juicer.log)
Is this running result normal? I have a sense that something is a little off.

**Comment by chenzhao12** [comment]
I encountered the same problem, have you solved it?

**Comment by yuntan1992** [comment]
I couldn't find a solution, so I ended up switching to Juicer version 1.6.


| |
允郯
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/15/2023 09:43 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [aidenlab/juicer] ***! Error! Either inter.hic or inter_30.hic were not created (Issue #330) |

I encountered the same problem, have you solved it?

**Comment by jlchen5** [comment]
I met the same problem with jucier 2.0:
~~~
bash scripts/juicer.sh -d ~/Yasmine/HiCData/juicer -D ~/Yasmine/HiCData/juicer -y ~/Yasmine/HiCData/juicer/hg19_MseI.txt -z ~/Yasmine/HiCData/juicer/reference/BWAIndex/hg19.fa -p ~/Yasmine/HiCData/juicer/hg19.chrom.sizes -s MseI -S "final"
Using /home/msbb/Yasmine/HiCData/juicer/hg19_MseI.txt as site file
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:96)
Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
	at juicebox.tools.HiCTools.main(HiCTools.java:96)
Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Using 1 CPU thread(s)
Not including fragment map
Error while reading graphs file: java.io.FileNotFoundException: /home/msbb/Yasmine/HiCData/juicer/aligned/inter_hists.m (No such file or directory)
Start preprocess
Writing header
Writing body
......................
Writing footer
 
Finished preprocess
Done creating .hic file. Normalization not calculated due to -n flag.
To run normalization, run: juicebox addNorm <hicfile>
 
real	0m3.653s
user	0m11.543s
sys	0m0.922s
Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Using 1 CPU thread(s)
 
Calculating norms for zoom BP_2500000java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
	at juicebox.tools.utils.norm.NormalizationCalculations.computeVC(NormalizationCalculations.java:355)
	at juicebox.tools.utils.norm.NormalizationVectorUpdater.buildVCOrVCSQRT(NormalizationVectorUpdater.java:186)
	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:139)
	at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:128)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)
 
real	0m0.545s
user	0m1.676s
sys	0m0.579s
Fri Dec 15 13:09:57 CET 2023
Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Using 1 CPU thread(s)
Not including fragment map
Error while reading graphs file: java.io.FileNotFoundException: /home/msbb/Yasmine/HiCData/juicer/aligned/inter_30_hists.m (No such file or directory)
Start preprocess
Writing header
Writing body
......................
Writing footer
 
Finished preprocess
Done creating .hic file. Normalization not calculated due to -n flag.
To run normalization, run: juicebox addNorm <hicfile>
 
real	0m3.551s
user	0m11.683s
sys	0m0.946s
Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Using 1 CPU thread(s)
 
Calculating norms for zoom BP_2500000java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
	at juicebox.tools.utils.norm.NormalizationCalculations.computeVC(NormalizationCalculations.java:355)
	at juicebox.tools.utils.norm.NormalizationVectorUpdater.buildVCOrVCSQRT(NormalizationVectorUpdater.java:186)
	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:139)
	at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:128)
	at juicebox.tools.HiCTools.main(HiCTools.java:94)
 
real	0m0.520s
user	0m1.762s
sys	0m0.502s
/home/msbb/Yasmine/HiCData/juicer/scripts/common/juicer_postprocessing.sh: option requires an argument -- g
Usage: /home/msbb/Yasmine/HiCData/juicer/scripts/common/juicer_postprocessing.sh [-h] -j <juicer_tools_file_path> -i <hic_file_path> -m <bed_file_dir> -g <genome ID>
***! Error! Either inter.hic or inter_30.hic were not created
Either inter.hic or inter_30.hic were not created.  Check  for results
~~~

**Comment by z4668640** [comment]
me too. Have you found any solutions? 
I also noticed that there was this error at the same time
`/home/juicer-main/CPU/common/juicer_postprocessing.sh: option requires an argument -- g`
I forgot to specify the` -g` parameter when I started juicer.sh. This problem is solved when I use the parameter `-g hg19`.
> I met the same problem with jucier 2.0:
> 
> ```
> bash scripts/juicer.sh -d ~/Yasmine/HiCData/juicer -D ~/Yasmine/HiCData/juicer -y ~/Yasmine/HiCData/juicer/hg19_MseI.txt -z ~/Yasmine/HiCData/juicer/reference/BWAIndex/hg19.fa -p ~/Yasmine/HiCData/juicer/hg19.chrom.sizes -s MseI -S "final"
> Using /home/msbb/Yasmine/HiCData/juicer/hg19_MseI.txt as site file
> Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
> 	at juicebox.tools.HiCTools.main(HiCTools.java:96)
> Picked up _JAVA_OPTIONS: -Xmx1024m -Xms1024m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Exception in thread "main" java.lang.RuntimeException: Unknown command: statistics
> 	at juicebox.tools.HiCTools.main(HiCTools.java:96)
> Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Using 1 CPU thread(s)
> Not including fragment map
> Error while reading graphs file: java.io.FileNotFoundException: /home/msbb/Yasmine/HiCData/juicer/aligned/inter_hists.m (No such file or directory)
> Start preprocess
> Writing header
> Writing body
> ......................
> Writing footer
>  
> Finished preprocess
> Done creating .hic file. Normalization not calculated due to -n flag.
> To run normalization, run: juicebox addNorm <hicfile>
>  
> real	0m3.653s
> user	0m11.543s
> sys	0m0.922s
> Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Using 1 CPU thread(s)
>  
> Calculating norms for zoom BP_2500000java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
> 	at juicebox.tools.utils.norm.NormalizationCalculations.computeVC(NormalizationCalculations.java:355)
> 	at juicebox.tools.utils.norm.NormalizationVectorUpdater.buildVCOrVCSQRT(NormalizationVectorUpdater.java:186)
> 	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:139)
> 	at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:128)
> 	at juicebox.tools.HiCTools.main(HiCTools.java:94)
>  
> real	0m0.545s
> user	0m1.676s
> sys	0m0.579s
> Fri Dec 15 13:09:57 CET 2023
> Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Using 1 CPU thread(s)
> Not including fragment map
> Error while reading graphs file: java.io.FileNotFoundException: /home/msbb/Yasmine/HiCData/juicer/aligned/inter_30_hists.m (No such file or directory)
> Start preprocess
> Writing header
> Writing body
> ......................
> Writing footer
>  
> Finished preprocess
> Done creating .hic file. Normalization not calculated due to -n flag.
> To run normalization, run: juicebox addNorm <hicfile>
>  
> real	0m3.551s
> user	0m11.683s
> sys	0m0.946s
> Picked up _JAVA_OPTIONS: -Xmx16000m -Xms16000m
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> Using 1 CPU thread(s)
>  
> Calculating norms for zoom BP_2500000java.lang.ArrayIndexOutOfBoundsException: Index 22 out of bounds for length 22
> 	at juicebox.tools.utils.norm.NormalizationCalculations.computeVC(NormalizationCalculations.java:355)
> 	at juicebox.tools.utils.norm.NormalizationVectorUpdater.buildVCOrVCSQRT(NormalizationVectorUpdater.java:186)
> 	at juicebox.tools.utils.norm.NormalizationVectorUpdater.updateHicFile(NormalizationVectorUpdater.java:139)
> 	at juicebox.tools.clt.old.AddNorm.run(AddNorm.java:128)
> 	at juicebox.tools.HiCTools.main(HiCTools.java:94)
>  
> real	0m0.520s
> user	0m1.762s
> sys	0m0.502s
> /home/msbb/Yasmine/HiCData/juicer/scripts/common/juicer_postprocessing.sh: option requires an argument -- g
> Usage: /home/msbb/Yasmine/HiCData/juicer/scripts/common/juicer_postprocessing.sh [-h] -j <juicer_tools_file_path> -i <hic_file_path> -m <bed_file_dir> -g <genome ID>
> ***! Error! Either inter.hic or inter_30.hic were not created
> Either inter.hic or inter_30.hic were not created.  Check  for results
> ```

**Comment by xusheng-code** [comment]
I also encountered the same problem with the newest version, and the result file "aligned" has "inter.hic" and "inter_30.hic" files, but no "merged_nodups.txt".

when I switched to Juicer version 1.6, the running information is:
(-: Looking for fastq files...fastq files exist
(-: Aligning files matching /home/user/juicer/work/fastq/*_R*.fastq*
 to genome hg19 with site file /home/user/juicer/restriction_sites/genome_DpnII.txt
(-: Created /home/user/juicer/work/splits and /home/user/juicer/work/aligned.

But, why aligning my hic files to genome hg19???

**Comment by OceanLyu** [comment]
By looking into juicer.sh, I found that if you do not specify the flag `-g`, `$genomeID` in this script would not be assigned any value, which possibly lead to the error. 

I think if you are working with your own genome, arbitrary setting of `-g` would be fine? $genomeID will just further be used for nominations for feature annotations in **juicer_postprocessing.sh**?
